### ISSUE TITLE
[dateMonths] or nothing is show for month name/number

### ISSUE THREAD

**Issue by sorenpeter** [GiovanniSalmeri/yellow-diary#1]
Hey,

When I try to use your diary extention for yellow the name of the month and day are not show or it shows [dateMonths] instead of January on  http://algorave.dk/events/
<img width="720" alt="Screenshot 2020-03-11 at 19 45 21" src="https://user-images.githubusercontent.com/8458421/76452166-f13ee600-63d0-11ea-8bcc-a3cf265b75c3.png">

How can I fix this?

Cheers

**Comment by GiovanniSalmeri** [comment]
Hello! I will investigate this issue tomorrow, thank you for bringing this to my attention. Perhaps there is something that needs updating, Yellow had several changes recently. Cheers

**Comment by GiovanniSalmeri** [comment]
There was a trivial error in the names of localised strings, which have changed recently in Yellow. I have fixed this, can you confirm that now all is OK? Cheers

**Comment by sorenpeter** [comment]
Yes, it works now. Thank you:)

**Comment by GiovanniSalmeri** [comment]
You're welcome!

**Comment by mave-git** [comment]
The problem appears while my testing today: no month names where shown. Looking in diary.php:

`$dateMonths = preg_split("/\s*,\s*/", $this->yellow->language->getText("coreDateMonths"));`

Changing from to '**_coreDateMonths_**' to '**_coreDateMonthsNominative_**' solved it (found in core.php):

`$dateMonths = preg_split("/\s*,\s*/", $this->yellow->language->getText("coreDateMonthsNominative"));`

**Comment by GiovanniSalmeri** [comment]
> The problem appears while my testing today: no month names where shown. Looking in diary.php:
> 
> `$dateMonths = preg_split("/\s*,\s*/", $this->yellow->language->getText("coreDateMonths"));`
> 
> Changing from to '**_coreDateMonths_**' to '**_coreDateMonthsNominative_**' solved it (found in core.php):
> 
> `$dateMonths = preg_split("/\s*,\s*/", $this->yellow->language->getText("coreDateMonthsNominative"));`

@mave-git Thank you very much for remarking this, I fixed the label. Actually I have used `coreDateMonthsGenitive`, since the name of month is used in a complete date. This makes a difference only for Slavic languages.

As a side-note: presently `coreDateMonthsGenitive` is correctly used only in Russian. Here are the correct strings for the other Slavic languages:

```
Czech:
CoreDateMonthsGenitive: Ledna, Února, Března, Dubna, Května, Června, Červenca, Srpna, Září, Října, Listopadu, Prosince

Slovak:
CoreDateMonthsGenitive: Januára, Februára, Marca, Apríla, Mája, Júna, Júla, Augusta, Septembra, Októbra, Novembra, Decembra

Russian:
CoreDateMonthsGenitive: Января, Февраля, Марта, Апреля, Мая, Июня, Июля, Августа, Сентября, Октября, Ноября, Декабря
```

I will make a PR as soon as possible...
