### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by JetGum** [GiovanniSalmeri/yellow-diary#8]
Dear Giovanni,

I gave your diary extension a shot on my website [james-joyce.de](https://www.james-joyce.de/). 

Unfortunately, while on localhost, I ran into fatal errors and array errors, depending on which example data I used (csv or psv). 
I have a feeling that the code does not quite match current Yellow standards, but I might be wrong.

Do you plan to update anytime soon?

Cheers, Carsten

**Comment by GiovanniSalmeri** [comment]
Thank you very much for reporting and sorry for the annoyance! I will check and fix the extension as soon as possible (hopefully in two or three days).

**Comment by GiovanniSalmeri** [comment]
@JetGum There were some silly errors in filenames and in constants. Could you check if all is working now? Thank you!

**Comment by JetGum** [comment]
@GiovanniSalmeri Great Giovanni, I will check as soon as I have access again to my computer (next week) Merry Xmas, btw

**Comment by JetGum** [comment]
@GiovanniSalmeri I did a fresh download to my local dev environment.
Do I need to enable simplexml somewhere for this to work on my localhost?

I tried existing diary files (csv, yaml etc), but get this when I add a shortcut. 

1. [diary events2019.csv] Frontend does not show any events.
2. [diary events2023.csv] I get these error messages:

```
Notice: Uninitialized string offset: 0 in /mnt/c/htdocs/yellow-dev/system/extensions/diary.php on line 248

Fatal error: Uncaught Error: Call to undefined function simplexml_load_file() in /mnt/c/htdocs/yellow-dev/system/extensions/diary.php:275 Stack trace: #0 /mnt/c/htdocs/yellow-dev/system/extensions/diary.php(294): YellowDiary->nominatim() #1 /mnt/c/htdocs/yellow-dev/system/extensions/diary.php(175): YellowDiary->geolocation() #2 /mnt/c/htdocs/yellow-dev/system/extensions/core.php(3073): YellowDiary->onParseContentShortcut() #3 /mnt/c/htdocs/yellow-dev/system/extensions/markdown.php(3890): YellowPage->parseContentShortcut() #4 [internal function]: YellowMarkdownParser->_doAutoLinks_shortcutBlock_callback() #5 /mnt/c/htdocs/yellow-dev/system/extensions/markdown.php(3879): preg_replace_callback() #6 /mnt/c/htdocs/yellow-dev/system/extensions/markdown.php(669): YellowMarkdownParser->doAutoLinks() #7 /mnt/c/htdocs/yellow-dev/system/extensions/markdown.php(3518): MarkdownParser->runSpanGamut() #8 /mnt/c/htdocs/yellow-dev/system/extensions/markdown.php(613): MarkdownExtraParser->formParagraphs() #9 /mnt/c/htdocs/yellow-dev/system in /mnt/c/htdocs/yellow-dev/system/extensions/diary.php on line 275
```

**Comment by GiovanniSalmeri** [comment]
Thank you very much for the feedback.

1. The notice about "Uninitialized string offset" should be fixed now.
2. The PHP extension `simplexml` is currently used only for `openstreetmap`. If you set `DiaryMaps: googlemaps` in `yellow-system.ini`, this PHP extension is not required. As soon as possible I will check if there is an easy manner to avoid it anyway.
3. Since the events in the example fils are all in the past, in order to show them you have to add the option `past`, for example `[diary events2019.csv past]`.

Sorry for the hassle!

**Comment by JetGum** [comment]
@GiovanniSalmeri 

1. is resolved
2. changed yellow-system.ini to googlemaps, no further errors entailed. On another [site](https://www.bankholiday.net/barcelona-city-break-holidays), I use your phantastic openstreetmap extension which works great there. Would be glad to show openstreetmap data / link with diary too.
3. displays now future/past events without errors.

Now I can start adding events and play around, thx for fixing this so fast!

Cheers

**Comment by GiovanniSalmeri** [comment]
> As soon as possible I will check if there is an easy manner to avoid it anyway.

Easier than expected! Now Openstreetmap/Nominatim uses the JSON output and so `simplexml` is no longer required. I do not remember why I chose to use the XML output... I am happy it is useful for you!

**Comment by JetGum** [comment]
Works like a charm, thx for the quick fix!

Cheers!
